- name: install nginx
  apt:
    name:
      - nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: start nginx
  service:
    name: nginx
    starte: started
  become: yes

- name: index
  template:
    src: index.html
    dest: /var/www/html/index.html
